// packages/react/src/components/Drawer.jsx
import { useMemo } from 'react'
import { Drawer as ArkDrawer } from '@ark-ui/react/drawer'
import { classNames } from 'syw-common/helpers'
import Icon from './Icon'

const Drawer = ({
	open = false,
	title,
	description,
	direction = 'bottom',
	onOpenChange,
	children,
	className
}) => {
	const handleOpenChange = (event) => {
		onOpenChange(event.open)
	}

	const swipeDirection = useMemo(() => {
		let safeSwipeDirection = direction
		if(direction === 'bottom') safeSwipeDirection = 'down'
		return safeSwipeDirection
	}, [direction])

	return (
		<ArkDrawer.Root
			open={open}
			swipeDirection={swipeDirection}
			modal={false}
			lazyMount={true}
			unmountOnExit={true}
			closeOnInteractOutside={true}
			onOpenChange={handleOpenChange}
		>
			{/* <Portal> */}
				<ArkDrawer.Backdrop
					className={classNames('DrawerBackdrop')}
				/>
				<ArkDrawer.Positioner
					className={classNames('DrawerPositioner')}
				>
					<ArkDrawer.Content
						className={classNames(
							className,
							'DrawerContent'
						)}
					>
						<ArkDrawer.Grabber
							className={classNames('DrawerGrabber')}
						>
							<ArkDrawer.GrabberIndicator
								className={classNames('DrawerGrabberIndicator')}
							/>
						</ArkDrawer.Grabber>
						<div
							className={classNames(
								'DrawerContentBox',
								'DrawerScrollable'
							)}
						>
							{title ?
								<hgroup
									className={classNames('DrawerContentHeader')}
								>
									{title ?
										<ArkDrawer.Title>
											{title}
										</ArkDrawer.Title>
									: null}
									{description ?
										<ArkDrawer.Description
											className='syw-hidden'
										>
											{description}
										</ArkDrawer.Description>
									: null}
								</hgroup>
							: null}
							{children}
						</div>
						<ArkDrawer.CloseTrigger
							className={classNames('DrawerClose')}
						>
							<Icon
								type="close"
							/>
						</ArkDrawer.CloseTrigger>
					</ArkDrawer.Content>
				</ArkDrawer.Positioner>
			{/* </Portal> */}
		</ArkDrawer.Root>
	)
}

export default Drawer

// packages/svelte/src/lib/components/Drawer.svelte
<script lang="ts">
	import { Drawer as ArkDrawer } from '@ark-ui/svelte/drawer'
	import { classNames } from 'syw-common/helpers'
	import Icon from './Icon.svelte'

	let {
		open = false,
		title,
		description,
		direction = 'bottom',
		onOpenChange,
		className,
		children
	} = $props()

	let swipeDirection = $derived.by(() => {
		let safeSwipeDirection = direction
		if(direction === 'bottom') safeSwipeDirection = 'down'
		return safeSwipeDirection
	})

	const handleOpenChange = (event: any) => {
		onOpenChange(event.open)
	}
</script>

<ArkDrawer.Root
	open={open}
	swipeDirection={swipeDirection}
	modal={false}
	lazyMount={true}
	unmountOnExit={true}
	closeOnInteractOutside={true}
	onOpenChange={handleOpenChange}
>
	<ArkDrawer.Backdrop
		class={classNames('DrawerBackdrop')}
	/>
	<ArkDrawer.Positioner
		class={classNames('DrawerPositioner')}
	>
		<ArkDrawer.Content
			class={classNames(
				className,
				'DrawerContent'
			)}
		>
			<ArkDrawer.Grabber
				class={classNames('DrawerGrabber')}
			>
				<ArkDrawer.GrabberIndicator
					class={classNames('DrawerGrabberIndicator')}
				/>
			</ArkDrawer.Grabber>
			<div
				class={classNames(
					'DrawerContentBox',
					'DrawerScrollable'
				)}
			>
				{#if title}
					<hgroup
						class={classNames('DrawerContentHeader')}
					>
						{#if title}
							<ArkDrawer.Title>
								{title}
							</ArkDrawer.Title>
						{/if}
						{#if description}
							<ArkDrawer.Description
								class='syw-hidden'
							>
								{description}
							</ArkDrawer.Description>
						{/if}
					</hgroup>
				{/if}
				{@render children?.()}
			</div>
			<ArkDrawer.CloseTrigger
				class={classNames('DrawerClose')}
			>
				<Icon
					type="close"
				/>
			</ArkDrawer.CloseTrigger>
		</ArkDrawer.Content>
	</ArkDrawer.Positioner>
</ArkDrawer.Root>
