// packages/react/src/components/ProvenanceDrawer.jsx
import { classNames } from 'syw-common/helpers'
import { useI18nContext, useUiContext, useDataContext } from '$src/context'
import Drawer from './Drawer'
import Provenance from './Provenance'

const ProvenanceDrawer = ({
	direction
}) => {
	const {
		isExplainerOpen,
		isProvenanceOpen,
		openProvenance,
		closeProvenance,
		closeExplainer
	} = useUiContext()
	const { getText } = useI18nContext()

	const handleOpenChange = (newOpen, event) => {
		const originalEvent = event
		if(newOpen) {
			openProvenance(originalEvent)
		} else {
			closeProvenance(originalEvent)
			closeExplainer(originalEvent)
		}
	}

	return (
		<Drawer
			open={isProvenanceOpen}
			title={getText("provenance", "toggle")}
			description=""
			direction={direction}
			onOpenChange={handleOpenChange}
			className={classNames('ProvenanceDrawer')}
		>
			<Provenance />
		</Drawer>
	)
}

export default ProvenanceDrawer

// packages/svelte/src/lib/components/ProvenanceDrawer.svelte
<script lang="ts">
	import { classNames } from 'syw-common/helpers'
    import { getUiContext } from '$lib/store/ui.js';
    import { getI18nContext } from '$lib/store/i18n.js';
	import Drawer from './Drawer.svelte'
	import Provenance from './Provenance.svelte'

	const {
		direction
	} = $props()
	
	const {
		isProvenanceOpen,
		openProvenance,
		closeProvenance,
		closeExplainer
	} = getUiContext()
	const {
		locale,
		getText
	} = getI18nContext()

	const handleOpenChange = (newOpen: boolean, event: any) => {
		const originalEvent = event
		if(newOpen) {
			openProvenance(originalEvent)
		} else {
			closeProvenance(originalEvent)
			closeExplainer(originalEvent)
		}
	}

</script>

<Drawer
	open={$isProvenanceOpen}
	title={getText($locale, 'provenance', 'toggle')}
	description=""
	direction={direction}
	onOpenChange={handleOpenChange}
	className={classNames('ProvenanceDrawer')}
>
	<Provenance />
</Drawer>
