// packages/react/src/components/ProvenancePopover.jsx
import { classNames } from 'syw-common/helpers'
import { useI18nContext, useUiContext, useDataContext } from '$src/context'
import Popover from './Popover'
import Provenance from './Provenance'

const ProvenancePopover = () => {
	const {
		isProvenanceOpen,
		openProvenance,
		closeProvenance,
		closeExplainer,
		elem
	} = useUiContext()
	const { getText } = useI18nContext()

	const handleOpenChange = (newOpen, event) => {
		if(newOpen) {
			openProvenance(event)
		} else {
			closeProvenance(event)
			closeExplainer(event)
		}
	}

	return (
		<Popover
			open={isProvenanceOpen}
			title={getText("provenance", "toggle")}
			onOpenChange={handleOpenChange}
			positioning={{
				placement: 'right-start',
				offset: {
					// mainAxis: 12,
					// crossAxis: -12
				},
				getAnchorRect: () =>
					elem?.querySelector('.Syw-ProvenanceToggle')?.getBoundingClientRect() ?? null
			}}
			className={classNames('ProvenancePopover')}
		>
			<Provenance />
		</Popover>
	)
}

export default ProvenancePopover

// packages/svelte/src/lib/components/ProvenancePopover.svelte
<script lang="ts">
	import { getI18nContext } from '$lib/store/i18n.js'
	import { getUiContext } from '$lib/store/ui.js'
	import Popover from './Popover.svelte'
	import Provenance from './Provenance.svelte'

	const {
		isProvenanceOpen,
		openProvenance,
		closeProvenance,
		closeExplainer,
		elem
	} = getUiContext()
	const { locale, getText } = getI18nContext()

	const handleOpenChange = (newOpen: boolean) => {
		if(newOpen) {
			openProvenance()
		} else {
			closeProvenance()
			closeExplainer()
		}
	}

</script>

<Popover
	open={$isProvenanceOpen}
	title={getText($locale, 'provenance', 'toggle')}
	onOpenChange={handleOpenChange}
	positioning={{
		placement: 'right-start',
		offset: {
			// mainAxis: 12,
			// crossAxis: -12
		},
		getAnchorRect: () =>
			$elem?.querySelector('.Syw-ProvenanceToggle')?.getBoundingClientRect() ?? null
	}}
	className='ProvenancePopover'
>
	<Provenance />
</Popover>
