// packages/svelte/src/lib/components/Manifest.svelte
<script lang="ts">
    import { Tabs, useTabs } from '@ark-ui/svelte/tabs';
	import { classNames, getAvailableTabs, getObjectValue } from 'syw-common/helpers'
	import { MANIFEST_CONTENT_TAB_KEYS } from 'syw-common/constants'
    import type { ManifestFieldKey } from 'syw-common/types';
	import type { Manifest as ManifestData } from 'syw-common/types/c2pa'
	import { getUiContext } from '$lib/store/ui.js'
	import Collapse from './Collapse.svelte'
	import ManifestPreview from './ManifestPreview.svelte'
    import ManifestContent from './ManifestContent.svelte';

	const { openManifests } = getUiContext();

	const {
		manifest,
		previewRef,
	}: {
		manifest: ManifestData
		previewRef?: ((el: HTMLElement | null) => void) | null
	} = $props()

	const open = $derived(String(manifest.id) in $openManifests)

	const tabKeys = $derived(
		((manifest?.type?.key ? getObjectValue(manifest.type.key, MANIFEST_CONTENT_TAB_KEYS) : undefined) ?? []) as ManifestFieldKey[]
	)

	const availableTabKeys = $derived(
		getAvailableTabs(tabKeys, manifest)
	)

	const tabs = $derived(useTabs({
		defaultValue: availableTabKeys[0]
	}))

	const classes = $derived(
		classNames(
			'Manifest',
			open ? 'Manifest_open' : false,
		)
	)
</script>

<div
	class={classes}
>
	<div
		class={classNames('ManifestInner')}
	>
		<Tabs.RootProvider
			value={tabs}
		>
			<ManifestPreview
				open={open}
				manifest={manifest}
				tabKeys={tabKeys}
				previewRef={previewRef}
			/>
			<Collapse
				open={open}
			>
				<ManifestContent
					manifest={manifest}
					tabKeys={tabKeys}
				/>
			</Collapse>
		</Tabs.RootProvider>
	</div>
</div>

// packages/react/src/components/Manifest.tsx
import { useCallback, useEffect, useMemo, useState } from 'react'
import type { RefObject } from 'react'
import { Tabs, useTabs } from '@ark-ui/react/tabs'
import { classNames, getAvailableTabs } from 'syw-common/helpers'
import { MANIFEST_CONTENT_TAB_KEYS } from 'syw-common/constants'
import type { Manifest as ManifestData } from 'syw-common/types/c2pa'
import { useUiContext } from '$src/context/ui'
import Collapse from './Collapse'
import ManifestPreview from './ManifestPreview'
import ManifestContent from './ManifestContent'

interface ManifestProps {
	manifest: ManifestData
	previewRef: RefObject<HTMLDivElement> | null
}

function Manifest({
	manifest,
	previewRef
}: ManifestProps) {
	const [open, setOpen] = useState(false)
	const { isProvenanceOpen, openManifests, openManifest, closeManifest } = useUiContext()

	const tabKeys = useMemo(() =>
		(manifest?.type?.key
			? MANIFEST_CONTENT_TAB_KEYS[manifest.type.key]
			: undefined
		) ?? []
	, [manifest])

	const availableTabKeys = useMemo(() =>
		getAvailableTabs(tabKeys, manifest)
	, [tabKeys, manifest])

	const tabs = useTabs({
		defaultValue: availableTabKeys?.[0]
	})

	const className = useMemo(() =>
		classNames(
			'Manifest',
			open ? 'Manifest_open' : null
		)
	, [open])

	// Handle click of manifest preview / header
	const handleToggle = useCallback((event?: unknown) => {
		setOpen(!open)
		if(open) {
			closeManifest(event, manifest)
		} else {
			openManifest(event, manifest)
		}
	}, [open, manifest, openManifest, closeManifest, openManifests])

	// Close manifest when provenance is closed
	useEffect(() => {
		if(!isProvenanceOpen) setOpen(false)
	}, [isProvenanceOpen])

	return (
		<div
			className={className}
		>
			<div
				className={
					classNames('ManifestInner')
				}
			>
				<Tabs.RootProvider
					value={tabs}
				>
					<ManifestPreview
						open={open}
						manifest={manifest}
						tabKeys={tabKeys}
						onToggle={handleToggle}
						previewRef={previewRef}
					/>
					<Collapse
						open={open && isProvenanceOpen}
					>
						<ManifestContent
							manifest={manifest}
							tabKeys={tabKeys}
						/>
					</Collapse>
				</Tabs.RootProvider>
			</div>
		</div>
	)
}

export default Manifest
