// packages/svelte/src/lib/components/Popover.svelte
<script lang="ts">
	import { Popover as ArkPopover } from '@ark-ui/svelte/popover'
	import { classNames } from 'syw-common/helpers'
    import type { PopoverProps } from 'syw-common/types';

	let {
		open = false,
		title,
		description,
		positioning,
		onOpenChange,
		className,
		children
	}: PopoverProps = $props()

	const handleOpenChange = (event: { open: boolean }) => {
		onOpenChange(event.open)
	}
</script>

<ArkPopover.Root
	open={open}
	modal={true}
	lazyMount={true}
	unmountOnExit={true}
	closeOnInteractOutside={true}
	positioning={positioning}
	onOpenChange={handleOpenChange}
>
	<!-- <Portal> -->
		<ArkPopover.Positioner
			class={classNames('PopoverPositioner')}
		>
			<ArkPopover.Content
				class={classNames(
					className,
					'PopoverContent'
				)}
			>
				<ArkPopover.Arrow
					class={classNames('PopoverArrow')}
				>
					<ArkPopover.ArrowTip />
				</ArkPopover.Arrow>
				<div
					class={classNames(
						'PopoverContentBox',
						'PopoverScrollable'
					)}
				>
					{#if title}
						<hgroup
							class={classNames('PopoverContentHeader')}
						>
							{#if title}
								<ArkPopover.Title
									class='syw-hidden'
								>
									{title}
								</ArkPopover.Title>
							{/if}
							{#if description}
								<ArkPopover.Description
									class='syw-hidden'
								>
									{description}
								</ArkPopover.Description>
							{/if}
						</hgroup>
					{/if}
					{@render children?.()}
				</div>
			</ArkPopover.Content>
		</ArkPopover.Positioner>
	<!-- </Portal> -->
</ArkPopover.Root>

// packages/react/src/components/Popover.jsx
import { useMemo } from 'react'
import { Popover as ArkPopover } from '@ark-ui/react/popover'
import { classNames } from 'syw-common/helpers'
import Icon from './Icon'

const Popover = ({
	open = false,
	title,
	description,
	direction = 'bottom',
	positioning,
	onOpenChange,
	children,
	className
}) => {


	const handleOpenChange = (event) => {
		onOpenChange(event.open)
	}

	return (
		<ArkPopover.Root
			open={open}
			modal={true}
			lazyMount={true}
			unmountOnExit={true}
			closeOnInteractOutside={true}
			positioning={positioning}
			onOpenChange={handleOpenChange}
		>
			{/* <Portal> */}
				<ArkPopover.Positioner
					className={classNames('PopoverPositioner')}
				>
					<ArkPopover.Content
						className={classNames(
							className,
							'PopoverContent'
						)}
					>
						<ArkPopover.Arrow
							className={classNames('PopoverArrow')}
						>
							<ArkPopover.ArrowTip />
						</ArkPopover.Arrow>
						<div
							className={classNames(
								'PopoverContentBox',
								'PopoverScrollable'
							)}
						>
							{title ?
								<hgroup
									className={classNames('PopoverContentHeader')}
								>
									{title ?
										<ArkPopover.Title
											className='syw-hidden'
										>
											{title}
										</ArkPopover.Title>
									: null}
									{description ?
										<ArkPopover.Description
											className='syw-hidden'
										>
											{description}
										</ArkPopover.Description>
									: null}
								</hgroup>
							: null}
							{children}
						</div>
					</ArkPopover.Content>
				</ArkPopover.Positioner>
			{/* </Portal> */}
		</ArkPopover.Root>
	)
}

export default Popover
